language: python
python:
  - "3.5"
install:
      - pip install Django #requirements.txt
script:
  - python manage.py test
addons:
  sonarcloud:
    organization: "piuc"
    token:
      secure: 
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
