# Generated by Django 2.1.1 on 2018-11-01 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlName', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=150)),
                ('keyword', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=30)),
                ('website', models.URLField(default='')),
                ('ORCID', models.CharField(default='', max_length=30)),
                ('scientific_area', models.CharField(default='', max_length=50)),
                ('confirmed_email', models.BooleanField(default=False)),
                ('profilePic', models.ImageField(default='profile_pics/profile_pic_placeholder.jpg', upload_to='profile_pics/')),
                ('favorites', models.ManyToManyField(to='feed.Post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
