# Generated by Django 2.1.1 on 2018-11-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='scientific_area',
            new_name='researchInterests',
        ),
    ]
