# Generated by Django 2.1.1 on 2018-10-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ORCID',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
