# Generated by Django 2.1.1 on 2018-09-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='texto_bonito',
            field=models.CharField(default='', max_length=500),
        ),
    ]
