# Generated by Django 2.1.1 on 2018-10-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarksmodel',
            name='keyword',
            field=models.CharField(default='', max_length=100),
        ),
    ]
