# Generated by Django 2.1.1 on 2018-10-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181004_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ORCID',
            field=models.CharField(default='', max_length=30),
        ),
    ]
