# Generated by Django 2.1.1 on 2018-11-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181101_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='researchInterests',
            field=models.CharField(default='', max_length=200),
        ),
    ]
