# Generated by Django 2.1.1 on 2018-10-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181004_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.CharField(default='', max_length=30),
        ),
    ]
