# Generated by Django 2.1.2 on 2018-11-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20181106_1447'),
        ('accounts', '0003_auto_20181101_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tweets',
            field=models.ManyToManyField(to='feed.Seartweet'),
        ),
    ]
