# Generated by Django 2.1.1 on 2018-11-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181101_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='redditRefreshToken',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
