# Generated by Django 2.1.1 on 2018-11-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_redditrefreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='redditRefreshToken',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
