# Generated by Django 2.1.3 on 2018-11-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181108_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='afiliacao',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subafiliacao',
            field=models.CharField(default='', max_length=500),
        ),
    ]
