# Generated by Django 2.1.3 on 2018-11-10 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181110_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='afiliacao',
            new_name='afiliation',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='subafiliacao',
            new_name='researchUnit',
        ),
    ]
