# Generated by Django 2.1.1 on 2018-11-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181109_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Twitter_SignedIn',
            field=models.BooleanField(default=False),
        ),
    ]
