# Generated by Django 2.1.2 on 2018-11-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20181113_1607'),
        ('accounts', '0008_auto_20181112_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tweets',
            field=models.ManyToManyField(to='feed.Seartweet'),
        ),
    ]
