# Generated by Django 2.1.1 on 2018-11-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_tweets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='subafiliation',
            new_name='unitresearch',
        ),
    ]
