# Generated by Django 2.1.2 on 2018-12-02 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20181118_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='unitresearch',
            new_name='subafiliation',
        ),
    ]
