# Generated by Django 2.1.2 on 2018-11-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seartweet',
            name='user',
        ),
    ]
