# Generated by Django 2.1.1 on 2018-09-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20180929_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Title', max_length=50),
            preserve_default=False,
        ),
    ]
