# Generated by Django 2.1.2 on 2018-11-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20181110_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seartweet',
            name='user',
        ),
        migrations.AddField(
            model_name='seartweet',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
