# Generated by Django 2.1.2 on 2018-11-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20181110_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seartweet',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
